apiVersion: v1
kind: ConfigMap
metadata:
  name: global-header-app-config
  namespace: {{ .Release.Namespace }}
data:
  global-header-app-config.yaml: |
    dynamicPlugins:
      frontend:
        red-hat-developer-hub.backstage-plugin-global-header:
          translationResources:
            - importName: globalHeaderTranslations
              ref: globalHeaderTranslationRef
          mountPoints:
            - mountPoint: application/header
              importName: GlobalHeader
              config:
                position: above-sidebar
            - mountPoint: global.header/component
              importName: CompanyLogo
              config:
                priority: 200
                props:
                  to: /
            - mountPoint: global.header/component
              importName: SearchComponent
              config:
                priority: 100
            - mountPoint: global.header/component
              importName: Spacer
              config:
                priority: 99
                props:
                  growFactor: 0
            - mountPoint: global.header/component
              importName: HeaderIconButton
              config:
                priority: 90
                props:
                  title: Self-service
                  titleKey: create.title
                  icon: add
                  to: create
            - mountPoint: global.header/component
              importName: StarredDropdown
              config:
                priority: 85
            - mountPoint: global.header/component
              importName: ApplicationLauncherDropdown
              config:
                priority: 82
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Documentation
                priority: 300
                props:
                  title: Developer Hub
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://docs.redhat.com/en/documentation/red_hat_developer_hub
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Documentation
                priority: 290
                props:
                  title: Openshift AI Docs
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Developer Tools
                priority: 200
                props:
                  title: RHDH Local
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://github.com/redhat-developer/rhdh-local
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Developer Tools
                priority: 190
                props:
                  title: RHDH Dynamic Plugin Factory
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://github.com/redhat-developer/rhdh-plugins
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Developer Tools
                priority: 180
                props:
                  title: RHDH CLI
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://github.com/redhat-developer/rhdh-cli
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Quick Links
                priority: 150
                props:
                  title: MCP Tools Guide
                  icon: https://upload.wikimedia.org/wikipedia/commons/0/01/Google_Docs_logo_%282014-2020%29.svg
                  link: https://docs.google.com/document/d/1o9qRYCAszGzTwW2mRjC4c9wFwJIx8J3XF1kGPFy5F1s/edit?tab=t.0
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Quick Links
                priority: 140
                props:
                  title: Openshift AI
                  icon: https://upload.wikimedia.org/wikipedia/commons/d/d8/Red_Hat_logo.svg
                  link: https://data-science-gateway.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
            - mountPoint: global.header/application-launcher
              importName: MenuItemLink
              config:
                section: Quick Links
                priority: 139
                props:
                  title: RHDH AI Rolling Demo Monitoring
                  icon: https://upload.wikimedia.org/wikipedia/commons/a/a1/Grafana_logo.svg
                  link: https://grafana-route-devcluster-monitoring.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
            - mountPoint: global.header/component
              importName: HelpDropdown
              config:
                priority: 80
            - mountPoint: global.header/help
              importName: SupportButton
              config:
                priority: 10
            - mountPoint: global.header/component
              importName: NotificationButton
              config:
                priority: 70
            - mountPoint: global.header/component
              importName: Divider
              config:
                priority: 50
            - mountPoint: global.header/component
              importName: ProfileDropdown
              config:
                priority: 10
            - mountPoint: global.header/profile
              importName: MenuItemLink
              config:
                priority: 100
                props:
                  title: Settings
                  titleKey: profile.settings
                  link: /settings
                  icon: manageAccounts
            - mountPoint: global.header/profile
              importName: MenuItemLink
              config:
                priority: 90
                props:
                  title: My profile
                  titleKey: profile.myProfile
                  type: myProfile
                  icon: account
            - mountPoint: global.header/profile
              importName: LogoutButton
              config:
                priority: 10
