{{- if not .Values.global.ci }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-lightspeed-postgres-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ (index .Values "redhat-developer-hub").nameOverride | default "redhat-developer-hub" | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backstage
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: lightspeed-postgres
          podSelector:
            matchLabels:
              app: postgres
      ports:
        - port: 5432
          protocol: TCP
{{- end }}
