apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rolling-demo-ns
  name: deployment-reader
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-deployments
  namespace: rolling-demo-ns
subjects:
  - kind: ServiceAccount
    name: default
    namespace: rolling-demo-ns
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
