apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-binding
  namespace: rolling-demo-ns
subjects:
  - kind: ServiceAccount
    name: k8s-sa
    namespace: rolling-demo-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
