kind: ConfigMap
apiVersion: v1
metadata:
  name: rcsconfig
  namespace: rolling-demo-ns
data:
  rcsconfig.yaml: |
    llm_providers:
      - name: dummy
        type: openai
        url: https://dummy.com
        models:
          - name: dummymodel
    ols_config:
      reference_content:
        product_docs_index_path: "./vector_db/rhdh_product_docs/1.7"
        product_docs_index_id: rhdh-product-docs-1_7
        embeddings_model_path: "./embeddings_model"
      conversation_cache:
        type: memory
        memory:
          max_entries: 1000
      authentication_config:
        module: "noop"
      default_provider: dummy
      default_model: dummymodel
      query_validation_method: disabled
      user_data_collection:
        feedback_disabled: false
        feedback_storage: "/app-root/tmp/data/feedback"
    dev_config:
      enable_dev_ui: false
      disable_auth: false
      disable_tls: true
      enable_system_prompt_override: true
    user_data_collector_config:
      ingress_url: "https://example.ingress.com/upload"
      user_agent: "example-agent"
